name: build

on:
  push:
    branches:
      - "**"

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:unit
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    if: github.ref == 'refs/heads/develop'
    defaults:
      run:
        working-directory: app
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_MINION_PAT }}
      - name: Build
        run: TAG=latest ./build.sh
      - run: npm ci
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_MINION_PAT }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: npx semantic-release

  deploy-staging:
    environment: Staging
    needs: build
    if: ${{ needs.build.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./pulumi
      - run: npm install -g pulumi
      - name: deploy
        run: STACK_NAME=staging VERSION=${{ needs.build.outputs.version }} app/deploy.sh
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

  deploy-production:
    environment: Production
    needs: [build, deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./pulumi
      - run: npm install -g pulumi
      - name: deploy
        run: STACK_NAME=production VERSION=${{ needs.build.outputs.version }} app/deploy.sh
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
