name: build

on:
  push:
    branches:
      - develop

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Build
        run: app/build.sh
