name: build

on:
  push:
    branches:
      - develop
      - add-release-it

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: app
      - name: git config
        run: |
          git config user.name "jbrunton-ci-minion"
          git config user.email "jbrunton-ci-minion@outlook.com"
      - name: release
        working-directory: app
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_MINION_PAT }}
      # - name: Docker Login
      #   run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # - name: Build Production
      #   if: github.ref_name == 'develop'
      #   run: TAG=latest DOCKER_PUSH=true app/build.sh
      # - name: Build Development
      #   if: github.ref_name != 'develop'
      #   run: DOCKER_PUSH=true app/build.sh
