name: build

on:
  push:
    branches:
      - develop

jobs:
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_MINION_PAT }}
      - name: Build
        run: ./build.sh
      - run: npm ci
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_MINION_PAT }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.CI_MINION_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.CI_MINION_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.CI_MINION_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.CI_MINION_EMAIL }}
        run: npx semantic-release

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./pulumi
      - run: npm install -g pulumi
      - name: deploy
        run: STACK_NAME=staging VERSION=${{ needs.build.outputs.version }} app/deploy.sh
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
