name: build

on:
  push:
    branches:
      - deploy-from-github

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./pulumi
      - id: pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
          work-dir: pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}