name: cleanup-stacks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      cutoff_days:
        type: string
        default: "3"
        description: Age in days of legacy dev stacks to clean up
        required: true

jobs:

  clean:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/app
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx ts-node cleanup-stacks
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          CUTOFF_DAYS: ${{ github.event.inputs.cutoff_days }}
