name: deploy-dev

on:
  
  pull_request:

jobs:
  
  build-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_MINION_PAT }}
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build
        id: build
        run: DOCKER_PUSH=true ./build.sh

  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        working-directory: pulumi
      - uses: pulumi/actions@ea444edc9d0c81cc7883c95bed84b67829c67503 # TODO: update to v3 after next release
        with:
          command: up
          stack-name: ${{ github.head_ref }}
          upsert: true
          work-dir: pulumi
          comment-on-pr: true
          github-token: ${{ secrets.CI_MINION_PAT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TAG: ${{ needs.build-dev.outputs.tag }}
